### ISSUE TITLE
mod加载后报错

### ISSUE THREAD

**Issue by Kw22mods** [xiaoye97/TaiWuCreateAvatarOptimization#1]
System.MissingMethodException: string ModManager.GetModPath(GameData.Domains.Mod.ModInfo)
  at TaiWuCreateAvatarOptimization.DelayMono.Update () [0x00026] in <bf312681b5314f33af9102472cd0225c>:0

**Comment by superexboom** [comment]
补充下吧，10/6更新的正式版，在开游戏的时候就已经提示出错了，在mod界面中看不到CAO

**Comment by xiaoye97** [comment]
Mod已更新并上传至创意工坊，删除本地mod之后从创意工坊订阅就可以了。
